- name: 创建监控程序及脚本目录
  file: path=/opt/monitor state=directory owner=root group=root mode=777
- name: 将node exporter传输到节点上
  copy: src=node_exporter dest=/opt/monitor/ mode=777
- name: 将监控脚本传输到节点上
  template: src=member.sh.j2 dest=/opt/monitor/member.sh mode=777
- name: 启动node exporter
  shell: nohup /opt/monitor/node_exporter > /opt/monitor/node_exporter.log 2>&1 &
- name: 配置定时任务，定时获取member节点运行数据并推送到pushgateway
  cron: name=crust-member-monitor minute=*/3 job=/opt/monitor/member.sh
- name: 安装系统排查工具
  apt: name=iotop state=latest update_cache=true
- name: 安装系统工具
  shell: apt-get update && apt-get install -y vim iftop net-tools sysstat
